apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontendport
  labels:
    name: frontend
    release: prometheus 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - env:
        - name: JAEGER_HOST
          value: backend-traces-agent.observability.svc.cluster.local
        name: frontend
        image: tkonthemove/observability_frontend:latest
        imagePullPolicy: Always
        ports:
        - name: frontendport
          containerPort: 8081
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend # service-monitor target
spec:
  selector:
    app: frontend # pod selection criteria
  ports:
    - name: frontend # must exist for prometheus scraping
      port: 8081
      protocol: TCP
      targetPort: frontendport
  type: LoadBalancer